# Generated by conceptadev/wayfinder release tooling.
class Wayfinder < Formula
  desc "Local knowledge validation, semantic search and MCP server"
  homepage "https://github.com/conceptadev/wayfinder"
  version "0.0.1-dev.1"
  license all_of: ["BSD-3-Clause", "Apache-2.0", "MIT"]
  depends_on "conceptadev/tap/okfp"

  on_macos do
    depends_on arch: :arm64
    url "https://github.com/conceptadev/wayfinder/releases/download/wayfinder-v0.0.1-dev.1/wayfinder-macos-arm64.tar.gz"
    sha256 "d2f2c3df68bd14a5e75d789c51468ccd5e144740a783c5f476e17cb82aec7249"
  end
  on_linux do
    depends_on arch: :x86_64
    url "https://github.com/conceptadev/wayfinder/releases/download/wayfinder-v0.0.1-dev.1/wayfinder-linux-x64.tar.gz"
    sha256 "09718f4dc6b6b72c76d16d88284f02c7cbe7868192f247b3f53175c114045d44"
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"bin/wayfinder"
  end

  test do
    assert_match "wayfinder #{version}", shell_output("#{bin}/wayfinder --version")
    assert_path_exists libexec/"models/embedding.gguf"
    assert_path_exists libexec/"licenses/objectbox/NOTICE"
  end
end
